package main

// Code generated by avro/gen. DO NOT EDIT.

// User is a generated struct.
type User struct {
	Name           string `avro:"name"`
	FavoriteNumber int64  `avro:"favorite_number"`
	FavoriteColor  string `avro:"favorite_color"`
}
