#!/bin/bash

# This should be run from the MSYS2 MinGW 64-bit shell to build librdkafka_windows.a
VERSION=v1.5.2
SRC_DIR=/mingw64/src/github.com/edenhill

RENAMED=0
function rename {
	# Hide these from cmake because we want the static libs
	pushd /mingw64/lib
	mv libzstd.dll.a libzstd.dll.a~
	mv libcrypto.dll.a libcrypto.dll.a~
	mv liblz4.dll.a liblz4.dll.a~
	mv libssl.dll.a libssl.dll.a~
	popd
	RENAMED=1
}

function derename {
	# Put these back
	pushd /mingw64/lib
	mv libzstd.dll.a~ libzstd.dll.a
	mv libcrypto.dll.a~ libcrypto.dll.a
	mv liblz4.dll.a~ liblz4.dll.a
	mv libssl.dll.a~ libssl.dll.a
	popd
	RENAMED=0
}

function errorcheck {
	if [ $? -ne 0 ]; then		
		if [ $RENAMED -eq 1 ]; then
			derename
		fi

		read -p "Press Enter to exit"
		exit 1
	fi
}

pacman -S --noconfirm --needed git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-zstd mingw-w64-x86_64-openssl mingw-w64-x86_64-lz4
errorcheck

mkdir -p $SRC_DIR
pushd $SRC_DIR
rm -rf librdkafka
git clone --depth 1 --branch $VERSION https://github.com/edenhill/librdkafka.git
errorcheck

rename

cd librdkafka

# WITH_SASL=OFF because we don't want cmake searching in the MinGW install
# for SASL libs, since Win32 SASL is handled natively
cmake \
    -G "MinGW Makefiles" \
    -D WITHOUT_WIN32_CONFIG=ON  \
    -D WITH_LIBDL=OFF \
    -D WITH_PLUGINS=OFF \
    -D WITH_SASL=OFF \
    -D WITH_SSL=ON \
    -D WITH_ZLIB=OFF \
    -D RDKAFKA_BUILD_STATIC=ON \
	-D RDKAFKA_BUILD_EXAMPLES=OFF \
	-D RDKAFKA_BUILD_TESTS=OFF .
errorcheck

mingw32-make
errorcheck

popd

mkdir -p mergescratch
pushd mergescratch

cp /mingw64/lib/libzstd.a ./
cp /mingw64/lib/libcrypto.a ./
cp /mingw64/lib/liblz4.a ./
cp /mingw64/lib/libssl.a ./
cp $SRC_DIR/librdkafka/src/librdkafka.a ./

ar -M < ../librdkafka_windows.mri
errorcheck

cp ./librdkafka_windows.a ../

popd
rm -rf mergescratch

cat >../build_windows.go <<EOF
// +build !dynamic


// This file was auto-generated by librdkafka/bundle-windows.sh, DO NOT EDIT.

package kafka

// #cgo CFLAGS: -I\${SRCDIR} -DLIBRDKAFKA_STATICLIB
// #cgo LDFLAGS: \${SRCDIR}/librdkafka/librdkafka_windows.a -lws2_32 -lsecur32 -lcrypt32
import "C"

// LibrdkafkaLinkInfo explains how librdkafka was linked to the Go client
const LibrdkafkaLinkInfo = "static windows built with Mingw-w64"
EOF

derename

exit
