#!/bin/bash
#
# Updates the bundled prebuilt librdkafka libraries to specified version.
#

set -e


usage() {
    echo "Usage: $0 <librdkafka-nuget-version>"
    echo ""
    echo "This tool must be run from the confluent-kafka-go/kafka/librdkafka directory"
    exit 1
}

download_nuget() {
    # Download nuget package
    local pkg=$1
    local version=$2

    # FIXME: download

    echo "$pkg.$version.nupkg"
}

extract_file() {
    # Extract file from archive
    local archive="$1"
    local apath="$2"  # file path in archive
    local dst="$3"  # destination file

    local tmpdir=$(mktemp -d tmpXXXXXX)

    unzip "$archive" -d "$tmpdir" "$apath"

    mv "$tmpdir/*" "$dst"

    rm -rf "$tmpdir"
}

parse_dynlibs() {
    # Parse dynamic libraries from pkg-config file
    local pc=$1
    local libs=
    local n=
    for n in $(grep ^Libs: $pc); do
        if [[ $n == -l* ]]; then
            libs="${libs} $n"
        fi
    done

    echo "$libs"
}

setup_build() {
    # Copies static library from the nupkg into final location,
    # extracts dynamic lib list from the nupkg's pkg-config file,
    # and generates the build_..go file
    local btype=$1
    local variant=
    local nupkg="$2"
    local zapath="$3"  # static library archive path in nupkg
    local apath="librdkafka-static_${btype}.go"
    local zpcpath=${2%.a}.pc

    extract_file $nupkg $zapath $apath

    extract_file $nupkg $zpcpath tmp.pc
    local dynlibs=$(parse_dynlibs $pc)
    rm -f tmp.pc

    echo "Generating ../build_${btype}.go"

    cat >../build_${btype}.go <<EOF
// +build !dynamic
// +build !static
// +build !static_all

// This file was auto-generated by librdkafka/setup.sh, DO NOT EDIT.

package kafka

// #cgo LDFLAGS: \${SRCDIR}/librdkafka/librdkafka_${btype}.a $dynlibs
import "C"

EOF

}


version=$1
[[ -n $version ]] || usage

nupkg=$(download_nuget librdkafka.redist $version)

setup_build glibc_linux $nupkg \
            build/native/lib/linux-x64/librdkafka-static.a
setup_build musl_linux $nupkg \
            build/native/lib/alpine-x64/librdkafka-static.a
setup_build osx $nupkg \
            build/native/lib/osx-x64/librdkafka-static.a


echo "All done"
