// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: my_record.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductName string `protobuf:"bytes,1,opt,name=productName,proto3" json:"productName,omitempty"`
}

func (x *MyRecord) Reset() {
	*x = MyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRecord) ProtoMessage() {}

func (x *MyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_my_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRecord.ProtoReflect.Descriptor instead.
func (*MyRecord) Descriptor() ([]byte, []int) {
	return file_my_record_proto_rawDescGZIP(), []int{0}
}

func (x *MyRecord) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

var File_my_record_proto protoreflect.FileDescriptor

var file_my_record_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x79, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2c, 0x0a, 0x08, 0x4d, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_my_record_proto_rawDescOnce sync.Once
	file_my_record_proto_rawDescData = file_my_record_proto_rawDesc
)

func file_my_record_proto_rawDescGZIP() []byte {
	file_my_record_proto_rawDescOnce.Do(func() {
		file_my_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_my_record_proto_rawDescData)
	})
	return file_my_record_proto_rawDescData
}

var file_my_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_my_record_proto_goTypes = []interface{}{
	(*MyRecord)(nil), // 0: main.MyRecord
}
var file_my_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_my_record_proto_init() }
func file_my_record_proto_init() {
	if File_my_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_my_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_my_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_my_record_proto_goTypes,
		DependencyIndexes: file_my_record_proto_depIdxs,
		MessageInfos:      file_my_record_proto_msgTypes,
	}.Build()
	File_my_record_proto = out.File
	file_my_record_proto_rawDesc = nil
	file_my_record_proto_goTypes = nil
	file_my_record_proto_depIdxs = nil
}
