// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     my_record.avsc
 */
package main

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type MyRecord struct {
	ProductName string `json:"productName"`
}

const MyRecordAvroCRC64Fingerprint = "w\x836\xab\x9d\xe9\x00\x15"

func NewMyRecord() MyRecord {
	r := MyRecord{}
	return r
}

func DeserializeMyRecord(r io.Reader) (MyRecord, error) {
	t := NewMyRecord()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeMyRecordFromSchema(r io.Reader, schema string) (MyRecord, error) {
	t := NewMyRecord()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeMyRecord(r MyRecord, w io.Writer) error {
	var err error
	err = vm.WriteString(r.ProductName, w)
	if err != nil {
		return err
	}
	return err
}

func (r MyRecord) Serialize(w io.Writer) error {
	return writeMyRecord(r, w)
}

func (r MyRecord) Schema() string {
	return "{\"fields\":[{\"name\":\"productName\",\"type\":\"string\"}],\"name\":\"MyRecord\",\"type\":\"record\"}"
}

func (r MyRecord) SchemaName() string {
	return "MyRecord"
}

func (_ MyRecord) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ MyRecord) SetInt(v int32)       { panic("Unsupported operation") }
func (_ MyRecord) SetLong(v int64)      { panic("Unsupported operation") }
func (_ MyRecord) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ MyRecord) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ MyRecord) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ MyRecord) SetString(v string)   { panic("Unsupported operation") }
func (_ MyRecord) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MyRecord) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.ProductName}

		return w

	}
	panic("Unknown field index")
}

func (r *MyRecord) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *MyRecord) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ MyRecord) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ MyRecord) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ MyRecord) HintSize(int)                     { panic("Unsupported operation") }
func (_ MyRecord) Finalize()                        {}

func (_ MyRecord) AvroCRC64Fingerprint() []byte {
	return []byte(MyRecordAvroCRC64Fingerprint)
}

func (r MyRecord) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["productName"], err = json.Marshal(r.ProductName)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *MyRecord) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["productName"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ProductName); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for productName")
	}
	return nil
}
