// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: cycle.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32       `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Next  *LinkedList `protobuf:"bytes,10,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *LinkedList) Reset() {
	*x = LinkedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedList) ProtoMessage() {}

func (x *LinkedList) ProtoReflect() protoreflect.Message {
	mi := &file_cycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedList.ProtoReflect.Descriptor instead.
func (*LinkedList) Descriptor() ([]byte, []int) {
	return file_cycle_proto_rawDescGZIP(), []int{0}
}

func (x *LinkedList) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LinkedList) GetNext() *LinkedList {
	if x != nil {
		return x.Next
	}
	return nil
}

var File_cycle_proto protoreflect.FileDescriptor

var file_cycle_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74,
	0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cycle_proto_rawDescOnce sync.Once
	file_cycle_proto_rawDescData = file_cycle_proto_rawDesc
)

func file_cycle_proto_rawDescGZIP() []byte {
	file_cycle_proto_rawDescOnce.Do(func() {
		file_cycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_cycle_proto_rawDescData)
	})
	return file_cycle_proto_rawDescData
}

var file_cycle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cycle_proto_goTypes = []interface{}{
	(*LinkedList)(nil), // 0: test.LinkedList
}
var file_cycle_proto_depIdxs = []int32{
	0, // 0: test.LinkedList.next:type_name -> test.LinkedList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cycle_proto_init() }
func file_cycle_proto_init() {
	if File_cycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cycle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cycle_proto_goTypes,
		DependencyIndexes: file_cycle_proto_depIdxs,
		MessageInfos:      file_cycle_proto_msgTypes,
	}.Build()
	File_cycle_proto = out.File
	file_cycle_proto_rawDesc = nil
	file_cycle_proto_goTypes = nil
	file_cycle_proto_depIdxs = nil
}
