// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: dep.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DependencyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsActive     bool         `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	TestMesssage *TestMessage `protobuf:"bytes,2,opt,name=test_messsage,json=testMesssage,proto3" json:"test_messsage,omitempty"`
}

func (x *DependencyMessage) Reset() {
	*x = DependencyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyMessage) ProtoMessage() {}

func (x *DependencyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyMessage.ProtoReflect.Descriptor instead.
func (*DependencyMessage) Descriptor() ([]byte, []int) {
	return file_dep_proto_rawDescGZIP(), []int{0}
}

func (x *DependencyMessage) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DependencyMessage) GetTestMesssage() *TestMessage {
	if x != nil {
		return x.TestMesssage
	}
	return nil
}

var File_dep_proto protoreflect.FileDescriptor

var file_dep_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x65, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a,
	0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x36, 0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dep_proto_rawDescOnce sync.Once
	file_dep_proto_rawDescData = file_dep_proto_rawDesc
)

func file_dep_proto_rawDescGZIP() []byte {
	file_dep_proto_rawDescOnce.Do(func() {
		file_dep_proto_rawDescData = protoimpl.X.CompressGZIP(file_dep_proto_rawDescData)
	})
	return file_dep_proto_rawDescData
}

var file_dep_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dep_proto_goTypes = []interface{}{
	(*DependencyMessage)(nil), // 0: test.DependencyMessage
	(*TestMessage)(nil),       // 1: test.TestMessage
}
var file_dep_proto_depIdxs = []int32{
	1, // 0: test.DependencyMessage.test_messsage:type_name -> test.TestMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dep_proto_init() }
func file_dep_proto_init() {
	if File_dep_proto != nil {
		return
	}
	file_test_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dep_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependencyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dep_proto_goTypes,
		DependencyIndexes: file_dep_proto_depIdxs,
		MessageInfos:      file_dep_proto_msgTypes,
	}.Build()
	File_dep_proto = out.File
	file_dep_proto_rawDesc = nil
	file_dep_proto_goTypes = nil
	file_dep_proto_depIdxs = nil
}
