// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: schemaregistry/test/proto/example.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id    int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Works []string `protobuf:"bytes,4,rep,name=works,proto3" json:"works,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schemaregistry_test_proto_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_schemaregistry_test_proto_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_schemaregistry_test_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetWorks() []string {
	if x != nil {
		return x.Works
	}
	return nil
}

type Pizza struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size     string   `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Toppings []string `protobuf:"bytes,2,rep,name=toppings,proto3" json:"toppings,omitempty"`
}

func (x *Pizza) Reset() {
	*x = Pizza{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schemaregistry_test_proto_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pizza) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pizza) ProtoMessage() {}

func (x *Pizza) ProtoReflect() protoreflect.Message {
	mi := &file_schemaregistry_test_proto_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pizza.ProtoReflect.Descriptor instead.
func (*Pizza) Descriptor() ([]byte, []int) {
	return file_schemaregistry_test_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *Pizza) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Pizza) GetToppings() []string {
	if x != nil {
		return x.Toppings
	}
	return nil
}

var File_schemaregistry_test_proto_example_proto protoreflect.FileDescriptor

var file_schemaregistry_test_proto_example_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22,
	0x42, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x22, 0x37, 0x0a, 0x05, 0x50, 0x69, 0x7a, 0x7a, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schemaregistry_test_proto_example_proto_rawDescOnce sync.Once
	file_schemaregistry_test_proto_example_proto_rawDescData = file_schemaregistry_test_proto_example_proto_rawDesc
)

func file_schemaregistry_test_proto_example_proto_rawDescGZIP() []byte {
	file_schemaregistry_test_proto_example_proto_rawDescOnce.Do(func() {
		file_schemaregistry_test_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_schemaregistry_test_proto_example_proto_rawDescData)
	})
	return file_schemaregistry_test_proto_example_proto_rawDescData
}

var file_schemaregistry_test_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schemaregistry_test_proto_example_proto_goTypes = []interface{}{
	(*Author)(nil), // 0: test.Author
	(*Pizza)(nil),  // 1: test.Pizza
}
var file_schemaregistry_test_proto_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schemaregistry_test_proto_example_proto_init() }
func file_schemaregistry_test_proto_example_proto_init() {
	if File_schemaregistry_test_proto_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schemaregistry_test_proto_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schemaregistry_test_proto_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pizza); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schemaregistry_test_proto_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemaregistry_test_proto_example_proto_goTypes,
		DependencyIndexes: file_schemaregistry_test_proto_example_proto_depIdxs,
		MessageInfos:      file_schemaregistry_test_proto_example_proto_msgTypes,
	}.Build()
	File_schemaregistry_test_proto_example_proto = out.File
	file_schemaregistry_test_proto_example_proto_rawDesc = nil
	file_schemaregistry_test_proto_example_proto_goTypes = nil
	file_schemaregistry_test_proto_example_proto_depIdxs = nil
}
