// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: example.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id      int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Picture []byte                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Works   []string               `protobuf:"bytes,4,rep,name=works,proto3" json:"works,omitempty"`
	// Types that are valid to be assigned to PiiOneof:
	//
	//	*Author_OneofMessage
	//	*Author_OneofString
	PiiOneof      isAuthor_PiiOneof `protobuf_oneof:"pii_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *Author) GetWorks() []string {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *Author) GetPiiOneof() isAuthor_PiiOneof {
	if x != nil {
		return x.PiiOneof
	}
	return nil
}

func (x *Author) GetOneofMessage() *Pizza {
	if x != nil {
		if x, ok := x.PiiOneof.(*Author_OneofMessage); ok {
			return x.OneofMessage
		}
	}
	return nil
}

func (x *Author) GetOneofString() string {
	if x != nil {
		if x, ok := x.PiiOneof.(*Author_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

type isAuthor_PiiOneof interface {
	isAuthor_PiiOneof()
}

type Author_OneofMessage struct {
	OneofMessage *Pizza `protobuf:"bytes,5,opt,name=oneof_message,json=oneofMessage,proto3,oneof"`
}

type Author_OneofString struct {
	OneofString string `protobuf:"bytes,6,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*Author_OneofMessage) isAuthor_PiiOneof() {}

func (*Author_OneofString) isAuthor_PiiOneof() {}

type Pizza struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Toppings      []string               `protobuf:"bytes,2,rep,name=toppings,proto3" json:"toppings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pizza) Reset() {
	*x = Pizza{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pizza) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pizza) ProtoMessage() {}

func (x *Pizza) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pizza.ProtoReflect.Descriptor instead.
func (*Pizza) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *Pizza) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Pizza) GetToppings() []string {
	if x != nil {
		return x.Toppings
	}
	return nil
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0xc2, 0x01, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x12, 0x32, 0x0a, 0x0d, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x50, 0x69, 0x7a, 0x7a, 0x61, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x0b, 0x0a,
	0x09, 0x70, 0x69, 0x69, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x37, 0x0a, 0x05, 0x50, 0x69,
	0x7a, 0x7a, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_goTypes = []any{
	(*Author)(nil), // 0: test.Author
	(*Pizza)(nil),  // 1: test.Pizza
}
var file_example_proto_depIdxs = []int32{
	1, // 0: test.Author.oneof_message:type_name -> test.Pizza
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	file_example_proto_msgTypes[0].OneofWrappers = []any{
		(*Author_OneofMessage)(nil),
		(*Author_OneofString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
