// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v7.35.1
// source: nested_decimal.proto

package test

import (
	types "github.com/confluentinc/confluent-kafka-go/v2/schemaregistry/confluent/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Two decimal fields, so a rule can compare one against the other and exercise a decimal
// reached by *selection* rather than one bound directly as `this`. Used by
// TestNestedProtoDecimalEquality.
type NestedDecimals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *types.Decimal         `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             *types.Decimal         `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedDecimals) Reset() {
	*x = NestedDecimals{}
	mi := &file_nested_decimal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedDecimals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedDecimals) ProtoMessage() {}

func (x *NestedDecimals) ProtoReflect() protoreflect.Message {
	mi := &file_nested_decimal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedDecimals.ProtoReflect.Descriptor instead.
func (*NestedDecimals) Descriptor() ([]byte, []int) {
	return file_nested_decimal_proto_rawDescGZIP(), []int{0}
}

func (x *NestedDecimals) GetA() *types.Decimal {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *NestedDecimals) GetB() *types.Decimal {
	if x != nil {
		return x.B
	}
	return nil
}

var File_nested_decimal_proto protoreflect.FileDescriptor

var file_nested_decimal_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x63, 0x6f,
	0x6e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0e, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x25, 0x0a,
	0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x6c,
	0x75, 0x65, 0x6e, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x01, 0x61, 0x12, 0x25, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x01, 0x62, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_nested_decimal_proto_rawDescOnce sync.Once
	file_nested_decimal_proto_rawDescData []byte
)

func file_nested_decimal_proto_rawDescGZIP() []byte {
	file_nested_decimal_proto_rawDescOnce.Do(func() {
		file_nested_decimal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nested_decimal_proto_rawDesc), len(file_nested_decimal_proto_rawDesc)))
	})
	return file_nested_decimal_proto_rawDescData
}

var file_nested_decimal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nested_decimal_proto_goTypes = []any{
	(*NestedDecimals)(nil), // 0: test.NestedDecimals
	(*types.Decimal)(nil),  // 1: confluent.type.Decimal
}
var file_nested_decimal_proto_depIdxs = []int32{
	1, // 0: test.NestedDecimals.a:type_name -> confluent.type.Decimal
	1, // 1: test.NestedDecimals.b:type_name -> confluent.type.Decimal
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nested_decimal_proto_init() }
func file_nested_decimal_proto_init() {
	if File_nested_decimal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nested_decimal_proto_rawDesc), len(file_nested_decimal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nested_decimal_proto_goTypes,
		DependencyIndexes: file_nested_decimal_proto_depIdxs,
		MessageInfos:      file_nested_decimal_proto_msgTypes,
	}.Build()
	File_nested_decimal_proto = out.File
	file_nested_decimal_proto_goTypes = nil
	file_nested_decimal_proto_depIdxs = nil
}
