// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
package recordname

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapBasicPerson(r map[string]BasicPerson, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeBasicPerson(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapBasicPersonWrapper struct {
	Target *map[string]BasicPerson
	keys   []string
	values []BasicPerson
}

func (_ *MapBasicPersonWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapBasicPersonWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapBasicPersonWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]BasicPerson, 0, s)
	}
}

func (r *MapBasicPersonWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapBasicPersonWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapBasicPersonWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v BasicPerson
	v = NewBasicPerson()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapBasicPersonWrapper) AppendArray() types.Field { panic("Unsupported operation") }
