// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
package recordname

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionStringTypeEnum int

const (
	UnionStringTypeEnumString UnionStringTypeEnum = 0
)

type UnionString struct {
	String    string
	UnionType UnionStringTypeEnum
}

func writeUnionString(r UnionString, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionStringTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for UnionString")
}

func NewUnionString() UnionString {
	return UnionString{}
}

func (r UnionString) Serialize(w io.Writer) error {
	return writeUnionString(r, w)
}

func DeserializeUnionString(r io.Reader) (UnionString, error) {
	t := NewUnionString()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionStringFromSchema(r io.Reader, schema string) (UnionString, error) {
	t := NewUnionString()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r UnionString) Schema() string {
	return "[\"string\"]"
}

func (_ UnionString) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ UnionString) SetInt(v int32)      { panic("Unsupported operation") }
func (_ UnionString) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ UnionString) SetDouble(v float64) { panic("Unsupported operation") }
func (_ UnionString) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ UnionString) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionString) SetLong(v int64) {

	r.UnionType = (UnionStringTypeEnum)(v)
}

func (r *UnionString) Get(i int) types.Field {

	switch i {
	case 0:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ UnionString) NullField(i int)                  { panic("Unsupported operation") }
func (_ UnionString) HintSize(i int)                   { panic("Unsupported operation") }
func (_ UnionString) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ UnionString) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ UnionString) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ UnionString) Finalize()                        {}

func (r UnionString) MarshalJSON() ([]byte, error) {

	switch r.UnionType {
	case UnionStringTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for UnionString")
}

func (r *UnionString) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for UnionString")
}
