// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
package recordname

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionLongNullTypeEnum int

const (
	UnionLongNullTypeEnumLong UnionLongNullTypeEnum = 0
)

type UnionLongNull struct {
	Long      int64
	Null      *types.NullVal
	UnionType UnionLongNullTypeEnum
}

func writeUnionLongNull(r *UnionLongNull, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(1, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionLongNullTypeEnumLong:
		return vm.WriteLong(r.Long, w)
	}
	return fmt.Errorf("invalid value for *UnionLongNull")
}

func NewUnionLongNull() *UnionLongNull {
	return &UnionLongNull{}
}

func (r *UnionLongNull) Serialize(w io.Writer) error {
	return writeUnionLongNull(r, w)
}

func DeserializeUnionLongNull(r io.Reader) (*UnionLongNull, error) {
	t := NewUnionLongNull()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionLongNullFromSchema(r io.Reader, schema string) (*UnionLongNull, error) {
	t := NewUnionLongNull()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionLongNull) Schema() string {
	return "[\"long\",\"null\"]"
}

func (_ *UnionLongNull) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionLongNull) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionLongNull) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionLongNull) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionLongNull) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionLongNull) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionLongNull) SetLong(v int64) {

	r.UnionType = (UnionLongNullTypeEnum)(v)
}

func (r *UnionLongNull) Get(i int) types.Field {

	switch i {
	case 0:
		return &types.Long{Target: (&r.Long)}
	case 1:
		return r.Null
	}
	panic("Unknown field index")
}
func (_ *UnionLongNull) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionLongNull) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionLongNull) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionLongNull) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionLongNull) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionLongNull) Finalize()                        {}

func (r *UnionLongNull) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionLongNullTypeEnumLong:
		return json.Marshal(map[string]interface{}{"long": r.Long})
	}
	return nil, fmt.Errorf("invalid value for *UnionLongNull")
}

func (r *UnionLongNull) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["long"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Long)
	}
	return fmt.Errorf("invalid value for *UnionLongNull")
}
