package main

// Code generated by avro/gen. DO NOT EDIT.

// User is a generated struct.
type User struct {
	Name           string `avro:"name"`
	FaveNum        int64  `avro:"fave_num"`
	FavoriteColor  string `avro:"favorite_color"`
}
