services:
  broker-1:
    image: apache/kafka:4.0.0
    restart: unless-stopped
    container_name: broker-1
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./kraft/server.properties:/mnt/shared/config/server.properties
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"

