// +build !dynamic


// This file was auto-generated by librdkafka/bundle-windows.sh, DO NOT EDIT.

package kafka

// #cgo CFLAGS: -I${SRCDIR} -DLIBRDKAFKA_STATICLIB
// #cgo LDFLAGS: ${SRCDIR}/librdkafka/librdkafka_windows.a -lws2_32 -lsecur32 -lcrypt32
import "C"

// LibrdkafkaLinkInfo explains how librdkafka was linked to the Go client
const LibrdkafkaLinkInfo = "static windows built with Mingw-w64"
