// +build !dynamic
// +build !static
// +build !static_all

// This file was auto-generated by librdkafka/setup.sh, DO NOT EDIT.

package kafka

// #cgo LDFLAGS: ${SRCDIR}/librdkafka/librdkafka_darwin.a -lm -lsasl2 -lz -ldl -lpthread
import "C"

