apiVersion: v1alpha
kind: Project
metadata:
  name: confluent-kafka-go
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/confluent-kafka-go.git
    run_on:
    - branches
    - tags
    - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - master
      - "/^v\\d+\\.\\d+\\.x$/"